File "./syntax/invalid/unexpected_catch2.sk", line 2, characters 6-10:
Expected '}'. Found 'catch'.
1 | fun main(): String {
2 |   "" catch { Exception _ -> "" }
  |      ^^^^^
3 | }

File "./syntax/invalid/unexpected_catch2.sk", line 1, characters 20-20:
 For opening '{'
1 | fun main(): String {
  |                    ^
2 |   "" catch { Exception _ -> "" }
