class StrExn(x: String) extends Exception {
  fun getMessage(): String {
    this.x
  }
}

fun foo(): String {
  throw StrExn("Pass\n")
}

fun useless{a: String, b: String}: String {
  "Fail"
}

fun main(): void {
  print_raw(
    try {
      useless{b => foo(), a => throw StrExn("Fail")}
    } catch {
    | StrExn(s) -> s
    | _ -> "Fail"
    }
  )
}
