fun main(): void {
  print_raw(
    try {
      foo()
    } catch {
    | _ -> "Pass\n"
    }
  )
}

class MyException() extends Exception {
  fun getMessage(): String {
    "MyException error"
  }
}

fun foo<T>(): T {
  throw MyException()
}
